---
title: "DataImport"
author: "Philipp Peter & Laurenz Harnischmacher & Nico Lindert"
date: "11 Mai 2019"
output: html_document
---
## definie enviromentpath
```{r "knitr config", cache = FALSE, include=FALSE}
require("knitr")
#nico_root
#knitr::opts_knit$set(root.dir = "F:/Github/ourdata/data")

#Philipp_root
#knitr::opts_knit$set(root.dir = "C:\\Users\\Philipp\\Documents\\StudDocs\\Master\\SS2019\\Programming Data Science\\data")

knitr::opts_knit$set(root.dir = "C:\\Users\\Philipp\\Documents\\Meine Dokumente\\StudiumDocs\\Master\\2019 SS\\Programming Data Science\\data")

#laurenz_root
#knitr::opts_knit$set(root.dir = "C:\\Users\\Laure\\Documents\\git_Repositories\\phyk_data")

```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Get the data 

```{r}
library(tidyverse)
library(stringi)
library(hms)

rootDir <- knitr::opts_knit$get("root.dir")
headersPath <- paste(rootDir, "01_data_understanding/order_columns.txt", sep="/")
dataPath <- paste(rootDir, "00_raw_data/order_data.csv", sep="/")

# prepare column name list
headersFile = file(headersPath, "r")
headerNames <- list()
#http://r.789695.n4.nabble.com/How-to-read-plain-text-documents-into-a-vector-td901794.html
obj_list <- readLines(headersFile)

#To convert to a vector, do the following:
result <- stri_extract_first(obj_list, regex="[A-z ,]+")
dtype <- stri_extract_last(obj_list, regex="[A-z ,]+")
result <- gsub(" ", "_", result)

dataframe <- read_csv(dataPath, col_names = result, na=c("", "?", "NULL", "NA", "Nan"), guess_max = 3400)
dataframe$order_time <- parse_time(dataframe$"Order_Line_Date_Time","%H\\:%M\\:%S")
head(dataframe)
```

## Replacing "?" and "NULL" with nan
```{r}
library(naniar)
na_strings <- c("?", "NULL")
df2 <- dataframe %>% replace_with_na_all(condition = ~.x %in% na_strings)
## dataframe <- str_replace_all(dataframe, ";", ",")
head(df2)

```

## Clean_dataset
```{r}
#dataframe[colSums(!is.na(dataframe)) > 0]
dataframe <- dataframe[rowSums(!is.na(dataframe)) > 0,colSums(!is.na(dataframe)) > 0]
dataframe
```
```{r}
# Vergleiche Spalten, ob Dopplungen vorkommen
drop <- vector()
k <- 1
for (i in 1:ncol(dataframe)) {
  col_i = colnames(dataframe)[i]
  for (j in i+1:ncol(dataframe)){
    col_j = colnames(dataframe)[j]
    if(identical(dataframe[[col_i]],dataframe[[col_j]])) {
      # print(paste(col_i,col_j,sep=" = "))
      drop[k] <- j
      k <- k+1
    }
  }
}
print(drop)

# Lösche doppelte Spalten (immer die 2.)

dataframe <- subset(dataframe, select = -drop)
head(dataframe)
```

``` {r}
colnames(dataframe) <- str_replace(colnames(dataframe),"\\\\","")
# dataframe <- str_replace(dataframe, "\\\\", "/")
head(dataframe)
```

## create csv from dataframe
## compare py csv and r csv
``` {r}
write.csv(dataframe, file = "../00_raw_data/order_r.csv", row.names =FALSE, na = "")

# py csv
py_df = read.csv(file = "../00_raw_data/order_py.csv",na=c("", "?", "NULL", "NA", "Nan"), sep = ",",)

# r csv
r_df = read.csv(file = "../00_raw_data/order_r.csv",na=c("", "?", "NULL", "NA", "Nan"),sep = "," )

#head(r_df)
#head(py_df)
# show difference between python and r dataset
diff_r <-r_df[!(r_df%in%py_df)]
head(diff_r)
diff_p <-py_df[!(py_df%in%r_df)]
head(diff_p)

```
## Including Plots

You can also embed plots, for example:

```{r}



```



```{r}

#x = unique(dataframe$Order_Line_Session_ID)
#y = tabulate(match(dataframe$Order_Line_Session_ID, x))
x = as.POSIXct(paste(dataframe$Order_Line_Date, dataframe$order_time), format="%Y-%m-%d %H:%M:%S")


ggplot(dataframe) + 
  geom_point(mapping = aes(x = x, y = dataframe$Order_Line_Amount, color=dataframe$Product_Level_)) +
  labs(
    x = "Time",
    y = "Shipping Amount",
    colour = "Product Level"
  )
ggplot(dataframe) + 
  geom_point(mapping = aes(x = x, y = dataframe$Order_Amount, colour = dataframe$Gender)) +
  labs(
    x = "Time",
    y = "Shipping Amount",
    colour = "Order Quantity"
  )


ggplot(data = dataframe)+
  geom_bar(mapping = aes(x = Order_Credit_Card_Brand, fill = Order_Credit_Card_Brand))


ggplot(data = dataframe)+
  geom_point(mapping = aes(x=Order_Line_Quantity,
                           y=Order_Amount, 
                           color=Gender))+
  facet_wrap(~Order_Credit_Card_Brand,nrow = 2)


ggplot(data = dataframe)+
  geom_point(mapping = aes(x=Order_Line_Quantity,
                           y=Order_Amount, 
                           color=Gender))+
  geom_smooth(mapping = aes(x=Order_Line_Quantity,
                           y=Order_Amount))

#headmap
Customer_Product_heatmap <- dataframe %>%
  select(US_State,Customer_ID,Order_Line_ID,Order_Line_Amount) %>%
  group_by(Customer_ID,US_State) %>%
  summarise(numberoforders= n(),totalspend=sum(Order_Line_Amount))

ggplot(data= Customer_Product_heatmap)+
  geom_tile(mapping = aes(x=US_State,y=Customer_ID, fill=totalspend))





```




```{r}
rootDir <- knitr::opts_knit$get("root.dir")
headersPath <- paste(rootDir, "experiment/experimental_results.csv", sep="/")
experiment <- read_csv(headersPath)
experiment <- experiment[1:147,]
t.test(experiment$random_recommendations, experiment$ranking_based)
```
Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
